[project]
name = "lockcell"
version = "0.2.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "pymonik",
]

[tool.uv.sources]
pymonik = { path = "../PymoniK/pymonik" }
